#https://github.com/envygeeks/jekyll-docker
ARG JEKYLL_VERSION
ARG CO_VERSION
FROM jekyll/jekyll:${JEKYLL_VERSION}

LABEL org.label-schema.vcs-url="https://github.com/gpupo/container-orchestration.git" \
      org.label-schema.schema-version="${CO_VERSION}" \
      org.label-schema.vendor="gpupo" \
      org.label-schema.name="container-orchestration" \
      org.label-schema.description="Image with Latest Jekyll" \
      org.label-schema.url="https://github.com/gpupo/container-orchestration"
