FROM willdurand/elk:latest

EXPOSE 80

LABEL org.label-schema.vcs-url="https://github.com/gpupo/container-orchestration.git" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="gpupo" \
      org.label-schema.name="container-orchestration" \
      org.label-schema.description="Image with Elasticsearch. Logstash. Kibana" \
      org.label-schema.url="https://github.com/gpupo/container-orchestration"
