ARG CO_VERSION
FROM jwilder/nginx-proxy

LABEL org.label-schema.vcs-url="https://github.com/gpupo/container-orchestration.git" \
      org.label-schema.schema-version="${CO_VERSION}" \
      org.label-schema.vendor="gpupo" \
      org.label-schema.name="container-orchestration" \
      org.label-schema.description="Image with NGINX proxy and HTTPS" \
      org.label-schema.url="https://github.com/gpupo/container-orchestration"
