# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.3

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

LABEL org.label-schema.vcs-url="https://github.com/gpupo/container-orchestration.git" \
      org.label-schema.schema-version="${CO_VERSION}" \
      org.label-schema.vendor="gpupo" \
      org.label-schema.name="container-orchestration" \
      org.label-schema.description="Image with Kibana" \
      org.label-schema.url="https://github.com/gpupo/container-orchestration"
